image: archlinux
packages:
  - go
  - yarn
  - wget
  - libappindicator-gtk3
sources:
  - https://git.sr.ht/~avery/crankshaft
artifacts:
  - crankshaft/crankshaft.tar.gz
tasks:
  - setup: |
      cd crankshaft
      go mod download
      cd injected
      yarn install --frozen-lockfile
  - test: |
      cd crankshaft
      make test
  - build: |
      cd crankshaft
      make release
      mv .dist "crankshaft-$(git rev-parse --short HEAD)"
      tar -czvf crankshaft.tar.gz "crankshaft-$(git rev-parse --short HEAD)"
triggers:
  - action: email
    condition: failure
    to: builds.sr.ht@avery.cafe
