image: archlinux
sources:
  - https://git.sr.ht/~avery/crankshaft
artifacts:
  - crankshaft/crankshaft.tar.gz
tasks:
  - packages: |
      sudo pacman -Sy --noconfirm archlinux-keyring && sudo pacman -Su --noconfirm
      sudo pacman -S --noconfirm go yarn wget libappindicator-gtk3
  - setup: |
      cd crankshaft
      go mod download
      cd injected
      yarn install --frozen-lockfile
  - test: |
      cd crankshaft
      make test
  - build: |
      cd crankshaft
      make build

      mkdir .dist
      # Get js-beautify binary
      # See source and build manifest at: https://builds.sr.ht/~avery/job/741873
      # TODO: this link expires in 90 days lol
      wget -O .dist/js-beautify https://patchouli.sr.ht/builds.sr.ht/artifacts/~avery/741873/249ceb5c7c3dfa54/js-beautify
      chmod +x .dist/js-beautify
      mv .dist "crankshaft-$(git rev-parse --short HEAD)"
      tar -czvf crankshaft.tar.gz "crankshaft-$(git rev-parse --short HEAD)"
triggers:
  - action: email
    condition: failure
    to: builds.sr.ht@avery.cafe
